import type { Meta, StoryObj } from "@storybook/react-vite";
import { useEffect, useRef } from "react";
import { ModelLabView } from "../oven/ModelLabView/ModelLabView";
import { PairedPreview, TerminalFrame, modelLabFrameEntries } from "../components/TerminalFrame/TerminalFrame";
import { modelLabFixture } from "../../../tui/src/catalog/model-lab-fixture";

type Checkpoint = typeof modelLabFixture.checkpoints[number];
function payload(checkpoint: Checkpoint) { return checkpoint === "unavailable" ? modelLabFixture.unavailable : checkpoint === "failure" ? modelLabFixture.failure : modelLabFixture.ready; }
function NativeModelLab({ checkpoint }: { checkpoint: Checkpoint }) { const value = payload(checkpoint), host = useRef<HTMLDivElement>(null); useEffect(() => { if (checkpoint === "unavailable") return; const iframe = host.current?.querySelector("iframe"), source = iframe?.contentWindow; if (!source) return; const stats = { ready: checkpoint === "ready", modelId: value.model.id, frameIndex: value.terminal.frame.index, frameId: value.terminal.frame.id, frameCount: value.terminal.frame.count, leafCount: value.model.leafCount, visibleLeafCount: value.terminal.metrics.visibleLeafCount, renderedLeafCount: value.terminal.metrics.renderedLeafCount, stableRootIdentity: true, stableLeafIdentityCount: value.terminal.metrics.stableLeafIdentityCount, connectedLeafCount: value.model.leafCount, childListMutationCount: 0, droppedSourcePolygonCount: 0, leafTags: Array(value.model.leafCount).fill("s"), runtimeConstruction: value.model.runtimeConstruction }; window.dispatchEvent(new MessageEvent("message", { source, origin: new URL(value.surface.url).origin, data: checkpoint === "ready" ? { schema: "polycss-model-lab-state@1", status: "ready", stats } : { schema: "polycss-model-lab-state@1", status: "error", error: "Producer reported surface failure" } })); }, [checkpoint, value]); return <div ref={host}><ModelLabView payload={value as never} /></div>; }
function PairedModelLab({ checkpoint = "ready", viewport = 78 }: { checkpoint?: Checkpoint; viewport?: 36 | 78 }) { const entry = modelLabFrameEntries.find((item) => item.checkpoint === checkpoint && item.viewport.width === viewport); return entry ? <PairedPreview consolePreview={<NativeModelLab checkpoint={checkpoint} />} terminalPreview={<TerminalFrame entry={entry} />} /> : <p role="status">No generated Model Lab frame exists.</p>; }
const meta = { title: "Ovens/Model Lab terminal", component: PairedModelLab, args: { checkpoint: "ready", viewport: 78 }, argTypes: { checkpoint: { control: "select", options: modelLabFixture.checkpoints }, viewport: { control: "select", options: [36, 78] } }, parameters: { layout: "centered", terminalParityOwner: "terminal-frame" } } satisfies Meta<typeof PairedModelLab>;
export default meta; export const Paired: StoryObj<typeof meta> = {};
