export const componentPairIds = [
  "alert",
  "badge",
  "button",
  "card",
  "checkbox",
  "field",
  "input",
  "progress",
  "select",
  "separator",
  "skeleton",
  "spinner",
  "table",
  "tabs",
  "textarea",
  "toggle-group",
  "tooltip",
  "copy-button",
  "dashboard-error",
  "empty-state",
  "filters",
  "field-list-cards",
  "top-card",
  "kpi-strip",
  "kpi-item",
  "metric-tiles",
  "progress-donut",
  "burn-donut",
  "waffle-metric",
  "visual-parity-media",
  "line-chart",
] as const;

export type ComponentPairId = typeof componentPairIds[number];

export const componentPairFixture = {
  alert: {
    title: "Verification passed",
    detail: "All required evidence is available for review.",
    tone: "success",
  },
  badge: { label: "active", tone: "accent" },
  button: { label: "Run burn", disabledLabel: "Unavailable" },
  card: {
    title: "Differential Testing",
    detail: "Exact-first comparison against the bound native source.",
    meta: "12 scenarios retained",
  },
  checkbox: { label: "Include completed Burnlists", checked: true },
  field: {
    label: "Repository path",
    value: "relative/path",
    detail: "The repository containing the Burnlist.",
    error: "Use an absolute repository path.",
  },
  input: { label: "Search Burnlists", value: "observer" },
  progress: { label: "Burnlist completion", value: 68 },
  select: {
    label: "Lifecycle",
    value: "active",
    options: ["draft", "ready", "active", "complete"],
  },
  separator: { before: "Current run", after: "Retained history" },
  skeleton: { label: "Loading Burnlist summary", rows: [18, 30, 22] },
  spinner: { label: "Loading result" },
  table: {
    caption: "Local Burnlists",
    headers: ["Project", "Burnlist", "Status", "Progress"],
    rows: [
      ["dashboard", "Observer layout", "Active", "27 / 31"],
      ["adapter-kit", "Contract acceptance", "Ready", "8 / 8"],
    ],
  },
  tabs: {
    label: "Burnlist lifecycle",
    tabs: ["Active", "Complete", "Blocked"],
    selected: "Active",
    panel: "Three Burnlists are cooking.",
  },
  textarea: {
    label: "Objective",
    value: "Describe the measurable outcome and required evidence.",
  },
  toggleGroup: {
    label: "Dashboard view",
    options: ["List", "Table", "Chart"],
    selected: "Table",
  },
  tooltip: {
    label: "Canonical state",
    detail: "The source used to derive this dashboard view.",
  },
  copyButton: { label: "Copy", value: "npm run verify" },
  dashboardError: { message: "The local Burnlist registry could not be read." },
  emptyState: {
    title: "No active Burnlists",
    detail: "Draft a Burnlist or change the lifecycle filter.",
  },
  filters: {
    label: "Burnlist lifecycle",
    options: ["Active", "Ready", "Draft", "Done", "All"],
    selected: "Active",
  },
  fieldListCards: {
    fields: [
      {
        id: "position", label: "Position", status: "failed", failures: 2, delta: 0.3,
        samples: [[0, 0, 0, 0], [1, 1, 1, 0], [2, 2, 2.1, 1], [3, 3, 3.3, 1], [4, 4, 4.05, 0], [5, 5, 5, 0]],
      },
      {
        id: "active", label: "Active", status: "pass", failures: 0, delta: 0.02,
        samples: [[0, 0, 0, 0], [1, 1, 1.02, 0], [2, 1, 1.01, 0], [3, 0, 0, 0], [4, 1, 1.01, 0], [5, 1, 1, 0]],
      },
    ],
  },
  topCard: {
    title: "Exact delta",
    historyTitle: "Run log",
    publishedAt: "2026-01-01T12:00:00.000Z",
    tasks: "2/3",
    elapsed: "30m",
    pace: "10m",
    done: "67%",
    log: "Frame 2 unchanged",
    chart: [
      { label: "F0", value: 0, state: "pass" },
      { label: "F1", value: 0.01, state: "pass" },
      { label: "F2", value: 0.1, state: "fail" },
      { label: "F3", value: 0.28, state: "fail" },
      { label: "F4", value: 0.04, state: "pass" },
      { label: "F5", value: 0, state: "pass" },
    ],
  },
  kpiStrip: {
    title: "Burnlist progress KPIs",
    items: [
      { heading: "Progress", value: "17 / 25", kind: "progress" },
      { heading: "Results", value: "6 · 2 · 1", kind: "burns" },
      { heading: "Fields", value: "2 / 12 failed", kind: "waffle" },
    ],
  },
  kpiItem: { heading: "Progress", value: "17 / 25 · 68%", percent: 68 },
  metricTiles: { passed: 17, total: 25, ratio: 0.08, meanAbsoluteDelta: 0.125, maximumAbsoluteDelta: 8 },
  progressDonut: { percent: 68, label: "68% complete" },
  burnDonut: {
    entries: [{ result: "improved" }, { result: "improved" }, { result: "unchanged" }, { result: "worsened" }, { result: "reverted" }],
    label: "2 improved · 1 worsened · 1 unchanged · 1 reverted",
  },
  waffleMetric: { metric: { total: 12, failed: 2, blocked: 1 }, label: "3 of 12 non-passing" },
  visualParityMedia: {
    label: "Homepage",
    frame: 7,
    images: [
      { label: "Current", source: "current", width: 2, height: 2 },
      { label: "Reference", source: "reference", width: 2, height: 2 },
      { label: "Difference", source: "difference", width: 2, height: 2 },
    ],
  },
  lineChart: {
    title: "Exact delta by frame",
    chartMode: "delta",
    points: [
      { label: "F0", value: 0, state: "pass" },
      { label: "F1", value: 0.01, state: "pass" },
      { label: "F2", value: 0.1, state: "fail" },
      { label: "F3", value: 0.28, state: "fail" },
      { label: "F4", value: 0.04, state: "pass" },
      { label: "F5", value: 0, state: "pass" },
    ],
  },
} as const;
