import { adaptDifferentialTesting } from "../../../dashboard/src/lib/differential-testing-adapter";
/** Canonical adapter-derived Differential data; no UI-only keys are mixed into payloads. */
const sha = "a".repeat(64), scenarioId = "135b757802521cd1", stamp = "2026-01-01T12:00:00.000Z";
const report = { id: "candidate-fixture", generatedAt: stamp, artifactSha256: sha, runtimeTreeSha256: sha, contractSha256: sha, scenarioId, frameCount: 3, replaySha256: sha, profileSha256: sha, result: "blocked", check: { status: "pass", id: "differential-testing-example-check@1", sha256: sha, subjectSha256: sha } } as const;
const refresh = { id: "refresh-fixture", status: "complete", scenarioId, event: { kind: "comparison-published", revision: sha, occurredAt: stamp }, requestedAt: stamp, startedAt: stamp, completedAt: stamp, error: null, report } as const;
const field = (id: string, label: string, failed: number, missing: number, samples: readonly (readonly [number, number | boolean, number | boolean | null, number])[]) => ({ id, label, sourceOwner: "engine/state", semantics: { meaning: `${label} after the update` }, unit: id === "position" ? "units" : null, tolerance: id === "position" ? 0.01 : 0, trustStatus: missing ? "blocked" : "pass", driftClass: missing ? "missing" : failed ? "mismatch" : "pass", driftReason: missing ? "One or more aligned samples are unavailable." : failed ? "One or more values exceed tolerance." : "All aligned values match.", sampleCount: samples.length, failedSampleCount: failed, missingSampleCount: missing, firstFailingTick: failed || missing ? 2 : null, maxDelta: id === "position" ? 0.1 : 0, samples });
const fields = [field("position", "Position", 1, 0, [[0, 0, 0, 0], [1, 1, 1.005, 0], [2, 2, 2.1, 1]]), field("active", "Active", 0, 0, [[0, false, false, 0], [1, true, true, 0], [2, true, true, 0]]), field("availability", "Availability", 0, 1, [[0, 1, 1, 0], [1, 1, 1, 0], [2, 1, null, 3]])] as const;
const normalRaw = { schema: "burnlist-differential-testing-data@1", publishedAt: stamp, title: "Differential Testing example", subtitle: "reference-fixture / candidate-fixture", adapter: { id: "differential-testing-example" }, trust: { status: "blocked", reportStatus: "blocked", blockers: ["Availability sample is missing."] }, scenarioCatalog: { selectedScenarioId: scenarioId, scenarios: [{ id: scenarioId, label: "reference-fixture", frameCount: 3, replaySha256: sha, profileSha256: sha, contractSha256: sha, updatedAt: stamp }] }, refresh, summary: { runs: { label: "Runs", total: 1, passed: 0, failed: 0, blocked: 1 }, fields: { label: "Fields", total: 3, passed: 1, failed: 1, blocked: 1 }, frames: { label: "Samples", total: 9, passed: 7, failed: 1, blocked: 1, uniqueTicks: 3 } }, progress: [{ timestamp: stamp, result: "blocked", value: 2, fieldCount: 3, failedFieldCount: 2, frames: 3, frame: 2, frameDelta: -1, refreshId: refresh.id, scenarioId, reportSha256: sha, runtimeTreeSha256: sha, contractSha256: sha }], log: [{ timestamp: stamp, result: "blocked", value: 2, delta: null, frame: 2, frames: 3, frameDelta: -1, failedFieldCount: 2, firstFailingTick: 2, firstFailingLabel: "Position", refreshId: refresh.id, scenarioId, reportSha256: sha, runtimeTreeSha256: sha, contractSha256: sha }], fields } as const;
const emptyRaw = { ...normalRaw, scenarioCatalog: { selectedScenarioId: null, scenarios: [] }, refresh: null, summary: { runs: { label: "Runs", total: 0, passed: 0, failed: 0, blocked: 0 }, fields: { label: "Fields", total: 0, passed: 0, failed: 0, blocked: 0 }, frames: { label: "Samples", total: 0, passed: 0, failed: 0, blocked: 0, uniqueTicks: 0 } }, progress: [], log: [], fields: [] } as const;
const failureRaw = { ...normalRaw, refresh: { id: refresh.id, status: "failed", scenarioId, event: refresh.event, requestedAt: stamp, startedAt: stamp, completedAt: stamp, error: "Full-scenario report failed." } } as const;
const normal = adaptDifferentialTesting(normalRaw as any) as any, empty = adaptDifferentialTesting(emptyRaw as any) as any, failure = adaptDifferentialTesting(failureRaw as any) as any;
export const differentialFixture = { id: "differential-testing", checkpoints: ["normal", "empty", "failure", "drill-down"] as const, payload: normal, empty, failure } as const;
