import type { JsonValue } from "../oven-runtime/terminal-contract";
export type ModelLabClient = Readonly<{ select(input: Readonly<{ sessionId: string; requestId: string; frameIndex: number }>): Promise<Readonly<{ status: "ready" | "error"; frame?: Readonly<{ index: number; id: string; count: number }> }>> }>;
type Fetch = (input: string, init?: RequestInit) => Promise<Response>;
const protocol = "burnlist-model-lab-terminal@1";
export function createModelLabClient({ endpoint, token, fetch: request = globalThis.fetch, retries = 2 }: { endpoint: string; token: string; fetch?: Fetch; retries?: number }): ModelLabClient {
  const parsed = new URL(endpoint); if (!new Set(["127.0.0.1", "localhost", "[::1]", "::1"]).has(parsed.hostname) || parsed.protocol !== "http:" || !token || !Number.isInteger(retries) || retries < 0 || retries > 4) throw new Error("Model Lab controller requires bounded loopback configuration."); const base = endpoint.replace(/\/+$/u, "");
  return { async select(input) { if (!/^[a-f0-9]{32}$/u.test(input.sessionId) || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,95}$/u.test(input.requestId) || !Number.isInteger(input.frameIndex) || input.frameIndex < 0) return { status: "error" }; const headers = { "content-type": "application/json", "x-burnlist-token": token }, body = { sessionId: input.sessionId, requestId: input.requestId, command: "set-frame", frameIndex: input.frameIndex };
    try { for (let attempt = 0; attempt <= retries; attempt += 1) { const response = await request(`${base}/api/model-lab-terminal/commands`, { method: "POST", headers, body: JSON.stringify(body) }); const command: any = await response.json(); if (!response.ok || command.schema !== protocol || command.sessionId !== input.sessionId || command.requestId !== input.requestId || command.frameIndex !== input.frameIndex) return { status: "error" }; if (command.status !== "complete") continue; if (!command.result?.ok || command.result.frameIndex !== input.frameIndex) return { status: "error" }; const stateResponse = await request(`${base}/api/model-lab-terminal/state?sessionId=${encodeURIComponent(input.sessionId)}`, { headers: { "x-burnlist-token": token } }); const state: any = await stateResponse.json(), frame = state?.state?.frame; if (stateResponse.ok && state.schema === protocol && state.status === "ready" && state.sessionId === input.sessionId && Number.isInteger(state.generation) && frame?.index === input.frameIndex && frame.id === `frame-${input.frameIndex}` && Number.isInteger(frame.count)) return { status: "ready", frame }; return { status: "error" }; } } catch { return { status: "error" }; }
    return { status: "error" };
  } };
}
export function applyVerifiedModelLabFrame(payload: JsonValue, frame: Readonly<{ index: number; id: string; count: number }>): JsonValue { const value = payload as any, { comparison, ...rest } = value; return { ...rest, model: { ...value.model, frameIndex: frame.index, frameId: frame.id }, terminal: { ...value.terminal, frame }, ...(comparison?.frameId === frame.id ? { comparison } : {}) }; }
